# -*- coding: utf-8 -*-
"""merge

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ua15Ja8x2nKhxuuYQN092xwKjVqVOn0M
"""

import pandas as pd
import numpy as np

cols = pd.read_csv('/content/drive/MyDrive/meesho/16.csv').columns.tolist()
cols = cols[1:]

import pandas as pd
from collections import Counter

csv_files = ['16.csv', '18.csv', '20.csv','28.csv', '32.csv','33.csv', 'comb4.csv']
dataframes = [pd.read_csv(f'/content/drive/MyDrive/meesho/'+file) for file in csv_files]
dataframes = [x[cols] for x in dataframes]

# Ensure all DataFrames have the same shape
for i in dataframes:
  print(i.shape)
if not all(df.shape == dataframes[0].shape for df in dataframes):
    raise ValueError("All CSV files must have the same shape.")

# Create an empty DataFrame to store the final result
result = pd.DataFrame(index=dataframes[0].index, columns=dataframes[0].columns)

# Iterate over each cell position
for row in range(dataframes[0].shape[0]):
    for col in dataframes[0].columns:
        # Collect all values from the five DataFrames for the current cell position
        values = [df.at[row, col] for df in dataframes]

        # Find the value with the maximum occurrence
        most_common_value = Counter(values).most_common(1)[0][0]

        # Set the most common value in the result DataFrame
        result.at[row, col] = most_common_value

# Save the resulting DataFrame to a new CSV file
result.to_csv('combined_max_occurrence.csv')

pd.read_csv('/content/combined_max_occurrence.csv', index_col = False).drop(columns = 'Unnamed: 0').to_csv('combined5_alll75.csv', index = False)

pd.read_csv('/content/combined5_alll75.csv')

pd.read_csv('/content/combined4_all75.csv', index_col = False)

